---
- name: Save the add_shard_to_cluster script
  template:
    src: templates/add_shard_to_cluster.js.j2
    dest: /tmp/add_shard_to_cluster.js
  run_once: true

- name: Change mongodb file permissions
  file:
    path: /var/lib/mongodb/
    owner: mongodb
    group: mongodb

- name: Start mongodb service
  include_tasks: service_start.yml

- name: Run the add_shard_to_cluster script
  shell: >
    mongosh
    --host {{ ansible_fqdn }}
    --port {{ rs_port }}
    < /tmp/add_shard_to_cluster.js
  run_once: true
  register: result
  until: result.rc == 0
  retries: 3
  delay: 3
  when: cluster_role != 'router'

- name: Stop services
  include_tasks: service_stop.yml