---
- name: Save the shard_add script
  template:
    src: templates/shard_add.js.j2
    dest: /tmp/shard_add.js

- name: Run the shard_add script
  shell: mongosh --port {{ rs_port }} < /tmp/shard_add.js >> {{ log_path }}/shard_add.log
  register: result
  until: result.rc == 0
  retries: 3
  delay: 3

- name: Remove the shard_add script
  file:
    path: /tmp/shard_add.js
    state: absent