---
- name: Clear logs
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ log_path }}/mongodb.log"
    - "{{ log_path }}/mongod.log"
    - "{{ log_path }}/mongos.log"
    - "{{ log_path }}/rs_init.log"
    - "{{ log_path }}/admin_init.log"
    - "{{ log_path }}/shard_add.log"
    - "{{ log_path }}/database_create.log"
