---
- name: Set the cfg_rs_servers variable
  set_fact:
    cfg_rs_servers: "{{ groups[cfg_server.group] | map('regex_replace', '$', ':{{ ports.config }}') | list }}"
  when: cfg_server is defined and cfg_server.group is defined

- name: Set config_db variable
  set_fact:
    config_db: "{{ cfg_server.name }}/{{ cfg_rs_servers | join(',') }}"

- name: Set rs_port
  set_fact:
    rs_port: "{{ ports[cluster_role] }}"

- name: Remove existing mongo config files
  file:
    dest: "{{ item.dest }}"
    state: absent
  with_items:
    - { dest: /lib/systemd/system/mongodb.service }
    - { dest: /lib/systemd/system/mongod.service }
    - { dest: /lib/systemd/system/mongos.service }
    - { dest: /etc/systemd/system/mongodb.service }
    - { dest: /etc/systemd/system/mongod.service }
    - { dest: /etc/systemd/system/mongos.service }
    - { dest: /etc/mongodb.conf }
    - { dest: /etc/mongod.conf }
    - { dest: /etc/mongos.conf }
    
- name: Put new mongo settings in place
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
    - { src: ../templates/mongod.service.j2, dest: /etc/systemd/system/mongod.service }
    - { src: ../templates/mongod.conf.j2, dest: /etc/mongod.conf }

- name: Reload the systemd daemon
  systemd:
    daemon_reload: yes