---

  - name: Stop services
    include: service-stop.yml

#  - name: Enable mongod service, if needed
#    become: true
#    service: name=mongod enabled=yes
#    when:
#      - stat_d.stat.exists
#      - mongodb_type == "daemon"
#
##  - name: Disable mongod service, if needed
##    become: true
##    service: name=mongod enabled=no
##    when:
##      - stat_d.stat.exists
##      - mongodb_type == "shard"
##

  - name: Copying daemon system file templates
    become: true
    template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode="u=rw,g=r,o=r"
    with_items:
      - { src: ../templates/mongod.service.j2, dest: /lib/systemd/system/mongod.service }
      - { src: ../templates/mongod.conf.j2, dest: /etc/mongod.conf }
    when: mongodb_type == "daemon" or mongodb_type == "standalone"

  - name: Remove daemon system files when n/a
    become: true
    file: dest={{ item.dest }} state=absent
    with_items:
      - { dest: /lib/systemd/system/mongod.service }
      - { dest: /etc/mongod.conf }
    when: mongodb_type == "daemon" or mongodb_type == "standalone"

  - name: Copying shard templates, if needed
    become: true
    template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode="u=rw,g=r,o=r"
    with_items:
      - { src: ../templates/mongos.service.j2, dest: /lib/systemd/system/mongos.service }
      - { src: ../templates/mongos.conf.j2, dest: /etc/mongos.conf }
    when: mongodb_type == "shard"

  - name: Enable mongos service, if needed
    become: true
    service: name=mongos enabled=yes
    when: mongodb_type == "shard"

  - name: Reload the systemd daemon
    command: systemctl daemon-reload
    become: true

  - name: Start the appropriate services
    include: service-start.yml
