---

  - name: Stop services
    include: service-stop.yml

  - name: Remove all mongo config files
    become: true
    file: dest={{ item.dest }} state=absent
    with_items:
      - { dest: /lib/systemd/system/mongodb.service }
      - { dest: /lib/systemd/system/mongod.service }
      - { dest: /lib/systemd/system/mongos.service }
      - { dest: /etc/systemd/system/mongodb.service }
      - { dest: /etc/systemd/system/mongod.service }
      - { dest: /etc/systemd/system/mongos.service }
      - { dest: /etc/mongodb.conf }
      - { dest: /etc/mongod.conf }
      - { dest: /etc/mongos.conf }

  - name: Copying mongod settings, if needed
    become: true
    template: src={{ item.src }} dest={{ item.dest }} # owner=root group=root mode="u=rw,g=r,o=r"
    with_items:
      - { src: ../templates/mongodb.daemon.service.j2, dest: /etc/systemd/system/mongodb.service }
      - { src: ../templates/mongodb.daemon.conf.j2, dest: /etc/mongodb.conf }
    when: mongodb_type == "daemon" or mongodb_type == "standalone"

  - name: Copying mongos settings, if needed
    become: true
    template: src={{ item.src }} dest={{ item.dest }} # owner=root group=root mode="u=rw,g=r,o=r"
    with_items:
      - { src: ../templates/mongodb.shard.service.j2, dest: /etc/systemd/system/mongodb.service }
      - { src: ../templates/mongodb.shard.conf.j2, dest: /etc/mongodb.conf }
    when: mongodb_type == "shard"

  - name: Reload the systemd daemon
    command: systemctl daemon-reload
    become: true

  - name: Enable mongodb service
    become: true
    service: name=mongodb enabled=yes

  - name: Start the appropriate services
    include: service-start.yml
