---
- name: Save the admin_init script
  template:
    src: templates/admin_init.js.j2
    dest: /tmp/admin_init.js

- name: Run the admin_init.js script
  shell: mongosh --host {{ ansible_fqdn }} --port {{ rs_port }} < /tmp/admin_init.js
  register: result

- name: Remove the admin_init script
  file:
    dest: /tmp/admin_init.js
    state: absent