---
- name: Save the create_database script
  ansible.builtin.template:
    src: templates/create_database.js.j2
    dest: /tmp/create_database.js
    mode: "0777"

- name: Run the create_database.js script
  ansible.builtin.shell: mongosh --port {{ rs_port }} < /tmp/create_database.js >> {{ log_path }}/database_create.log
  register: database_creation
  until: database_creation.rc == 0
  changed_when: database_creation.rc == 0

- name: Remove the create_database script
  ansible.builtin.file:
    dest: /tmp/create_database.js
    state: absent
