---
- name: Save the admin_init script
  ansible.builtin.template:
    src: templates/admin_init.js.j2
    dest: /tmp/admin_init.js
    mode: "0777"

- name: Run the admin_init.js script
  ansible.builtin.shell: mongosh --port {{ rs_port }} < /tmp/admin_init.js > {{ log_path }}/admin_init.log
  args:
    creates: "{{ log_path }}/admin_init.log"

- name: Remove the admin_init script
  ansible.builtin.file:
    dest: /tmp/admin_init.js
    state: absent

- name: Restart mongod service
  ansible.builtin.service:
    name: mongod
    state: restarted
