---
- name: Save the create_database script
  template:
    src: templates/create_database.js.j2
    dest: /tmp/create_database.js

- name: Run the create_database.js script
  shell: mongosh --port {{ rs_port }} < /tmp/create_database.js
  when: true

- name: Remove the create_database script
  file:
    dest: /tmp/create_database.js
    state: absent