---

  - debug: var=mongodb_db_name
  - debug: var=mongodb_db_user
  - debug: var=mongodb_db_password

# admin_password

  - name: Save the db_create script
    template: src=../templates/db_create.js.j2 dest=/tmp/db_create.js

  - name: Run the db_create script
    shell: >
      mongo
      --host {{ server_fqdn }}
      --port {{ rs_port }}
      --ssl
      --sslPEMKeyFile {{ sc_chain_remote }}
      --sslCAFile {{ sc_interm_remote }}
      < /tmp/db_create.js
    register: result

  - debug: var=result

#  - name: Run the db_create script
#
#    until: result.rc == 0
#    retries: 5
#    delay: 3
