---
- name: Create storage_path directory and set ownership
  file:
    path: "{{ storage_path }}"
    state: directory
    owner: mongodb
    group: mongodb
    mode: 0755

- name: Copy mongo keyfile
  copy:
    src: "{{ keyfile_src }}"
    dest: "{{ keyfile_path }}"
    owner: mongodb
    group: mongodb        
    mode: 0400

- name: Configuring the replica set
  set_fact:
    configuring_replica_set: true

- name: Upload init_replica_set config file
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Save the init_replica_set.js template to remote tmp
  template:
    src: templates/init_replica_set.js.j2
    dest: /tmp/init_replica_set.js
  run_once: true

- name: Start the appropriate services
  include_tasks: service_start.yml

- name: Delay
  pause:
    seconds: 5

- name: Run the init_replica_set.js script
  shell: mongosh --port {{ rs_port }} < /tmp/init_replica_set.js
  run_once: true
  register: res_rsi
  until: res_rsi.rc == 0
  retries: 3
  delay: 5

- name: Stop the daemon service
  service:
    name: mongod
    state: stopped

- name: Remove the init_replica_set.js script from remote tmp
  file:
    dest: /tmp/init_replica_set.js
    state: absent

- name: No longer configuring the replica set
  set_fact:
    configuring_replica_set: false

- name: Restore the mongodb configuration
  template:
    src: templates/mongod.conf.j2
    dest: /etc/mongod.conf
    owner: root
    group: root
    mode: u=rw,g=r,o=r