---
- name: Get release value
  command: lsb_release -sc
  register: lsb_release_out
  when: true

- name: Add an apt key by id from a keyserver
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present
  become: true

- name: Update APT Cache
  apt:
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - build-essential
      - gpg
    state: present
  become: true

- name: Variables
  set_fact:
    lsb_release: "{{ lsb_release_out.stdout }}"
    mongo_cfg: "{{ mongo_configs[mongo_version] }}"

- name: Save List
  template:
    src: templates/mongod.list.j2
    dest: /etc/apt/sources.list.d/mongod.list
    owner: root
    group: root
    mode: "u=rw,g=r,o=r"
  become: true

- name: Remove old mongodb packages
  apt:
    update_cache: yes
    name: mongodb
    state: absent

- name: Install the mongodb packages
  apt:
    name: mongodb-org
    state: present

- name: Autoremove unused packages
  apt:
    autoremove: yes
  become: true

- name: Full Upgrade
  apt:
    upgrade: dist

- name: Stop services
  include_tasks: service_stop.yml

- name: kill logs
  include_tasks: kill_logs.yml

- name: Start services
  include_tasks: service_start.yml
