---
- name: Get release value
  ansible.builtin.command: lsb_release -sc
  register: lsb_release_out
  when: true
  changed_when: lsb_release_out.rc == 0

- name: Add an apt key by id from a keyserver
  ansible.builtin.apt_key:
    url: https://www.mongodb.org/static/pgp/{{ mongo_configs[mongo_version].keyfile_name }}
    state: present

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages
  ansible.builtin.apt:
    name:
      - build-essential
      - gpg
    state: present

- name: Set lsb_release and mongo_cfg variables
  ansible.builtin.set_fact:
    lsb_release: "{{ lsb_release_out.stdout }}"
    mongo_cfg: "{{ mongo_configs[mongo_version] }}"

- name: Save mongod package list
  ansible.builtin.template:
    src: templates/mongod.list.j2
    dest: /etc/apt/sources.list.d/mongod.list
    owner: root
    group: root
    mode: u=rw,g=r,o=r

- name: Remove old mongodb packages
  ansible.builtin.apt:
    update_cache: true
    name: mongodb
    state: absent

- name: Autoremove unused packages
  ansible.builtin.apt:
    autoremove: true

- name: Install the mongodb packages
  ansible.builtin.apt:
    name: mongodb-org
    state: present
