---

  - name: get release value
    command: lsb_release -sc
    register: lsb_release_out

  - set_fact:
      lsb_release: "{{ lsb_release_out.stdout }}"

#  - debug: var=mongo_version
#  - debug: var=versions.ppa_pubkey

  - name: Add APT Key
    command: apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv {{ versions.ppa_pubkey[mongo_version] }}
    become: true

  - name: Save List
    template: src=../templates/mongodb.list.j2 dest=/etc/apt/sources.list.d/mongodb.list owner=root group=root mode="u=rw,g=r,o=r"
    become: true

  - name: Update APT Cache
    become: true
    apt:
      update_cache: yes

  - name: Remove old mongodb packages
    become: true
    apt:
      name: mongodb
      state: absent

  - name: Install the mongodb packages
    become: true
    apt:
      name: mongodb-org
      state: present

  - name: Autoremove unused
    become: true
    raw: sudo apt -y autoremove
#      apt:
#        autoremove: yes

  - name: Full Upgrade
    become: true
#    raw: apt -y full-upgrade
    apt:
      upgrade: dist

  - name: Stop services
    include_tasks: service-stop.yml

  - name: kill logs
    include_tasks: kill-logs.yml

  - name: Start services
    include_tasks: service-start.yml


