---
- name: Install mongo packages
  ansible.builtin.include_tasks: install_mongo.yml
  when: ((['install_mongo'] | intersect(flags)) | length > 0)

- name: Configure mongo
  ansible.builtin.include_tasks: configure_mongo.yml
  when: ((['configure_mongo'] | intersect(flags)) | length > 0)

- name: Start the mongo service
  ansible.builtin.include_tasks: start_mongo.yml
  when: ((['start_mongo'] | intersect(flags)) | length > 0)

- name: Stop the mongo service
  ansible.builtin.include_tasks: stop_mongo.yml
  when: ((['stop_mongo'] | intersect(flags)) | length > 0)

- name: Clear all sharded cluster logs
  ansible.builtin.include_tasks: clear_logs.yml
  when: ((['clear_logs'] | intersect(flags)) | length > 0)

- name: Prepare all cluster members
  ansible.builtin.include_tasks: prepare_members.yml
  when: ((['prepare_members'] | intersect(flags)) | length > 0)

- name: Init replica set
  ansible.builtin.include_tasks: init_replica.yml
  when: ((['init_replica'] | intersect(flags)) | length > 0)

- name: Create admin user
  ansible.builtin.include_tasks: create_admin.yml
  when: ((['create_admin'] | intersect(flags)) | length > 0)

- name: Add shard to cluster
  ansible.builtin.include_tasks: add_shard.yml
  when: ((['add_shard'] | intersect(flags)) | length > 0)

- name: Create database
  ansible.builtin.include_tasks: create_database.yml
  when: ((['create_database'] | intersect(flags)) | length > 0)
