---

  - include: prep-vars.yml

  - include: install-packages.yml
    when: pkg_install|bool == true

  - include: config-save.yml
    when: config_save|bool == true

  - include: replica-set-init.yml
    when: rs_init|bool == true

  - include: replica-set-shards.yml
    when: rs_shards|bool == true
