---

  - include: prep-vars.yml
    when: cluster_role is defined

  - include: install-packages.yml
    when: pkg_install|bool == true

  - include: storage-init.yml
    when: storage_init|bool == true

  - include: config-save.yml
    when: config_save|bool == true

  - include: replica-set-init.yml
    when: rs_init|bool == true

  - include: replica-set-shards.yml
    when: rs_shards|bool == true

  - include: db-create.yml
    when: db_create|bool == true

