---

  - include: prep-vars.yml
    when: cluster_role is defined

  - include: install-packages.yml
    tags: ['install']

  - include: storage-init.yml
    tags: ['storage_init']

  - include: config-save.yml
    tags: ['config_save']

  - include: replica-set-init.yml
    tags: ['rs_init']

  - include: replica-set-shards.yml
    tags: ['rs_shards']

  - include: db-create.yml
    tags: ['db_create']

