---

  - include: prep-vars.yml

  - include: install-packages.yml
    tags:
      - pkg_install

  - include: config-save.yml
    tags:
      - config

  - include: replica-set-init.yml
    when:
      - rs_init|bool == true

  - include: replica-set-shards.yml
    when:
      - rs_shards|bool == true
