---
- name: Install mongo packages
  include_tasks: install_mongo.yml
  when: ((['install_mongo'] | intersect(flags)) | length > 0)

- name: Save configuration
  include_tasks: save_configuration.yml
  when: ((['configure_mongo'] | intersect(flags)) | length > 0)

- name: Start the mongo service
  include_tasks: start_mongo.yml
  when: ((['start_mongo'] | intersect(flags)) | length > 0)

- name: Stop the mongo service
  include_tasks: stop_mongo.yml
  when: ((['stop_mongo'] | intersect(flags)) | length > 0)

- name: Reset storage
  include_tasks: reset_storage.yml
  when: ((['reset_storage'] | intersect(flags)) | length > 0)

- name: Init replica set
  include_tasks: init_replica.yml
  when: ((['init_replica'] | intersect(flags)) | length > 0)

- name: Create admin user
  include_tasks: create_admin.yml
  when: ((['create_admin'] | intersect(flags)) | length > 0)

- name: Add shard to cluster
  include_tasks: add_shard.yml
  when: ((['add_shard'] | intersect(flags)) | length > 0)

- name: Create database
  include_tasks: create_database.yml
  when: ((['create_database'] | intersect(flags)) | length > 0)
