---

# https://www.digitalocean.com/community/tutorials/how-to-implement-replication-sets-in-mongodb-on-an-ubuntu-vps
# https://www.digitalocean.com/community/tutorials/how-to-create-a-sharded-cluster-in-mongodb-using-an-ubuntu-12-04-vps
# https://docs.mongodb.com/manual/tutorial/deploy-shard-cluster/

  - include: prep-vars.yml

  - include: service-config.yml
    when: do_config|bool == true

  - include: replica-set-init.yml
    when: do_replica_set|bool == true
