---

# https://www.digitalocean.com/community/tutorials/how-to-implement-replication-sets-in-mongodb-on-an-ubuntu-vps
# https://www.digitalocean.com/community/tutorials/how-to-create-a-sharded-cluster-in-mongodb-using-an-ubuntu-12-04-vps
# https://docs.mongodb.com/manual/tutorial/deploy-shard-cluster/
# https://docs.mongodb.com/v3.2/tutorial/deploy-replica-set-with-keyfile-access-control/
# https://docs.mongodb.com/v3.2/tutorial/add-shards-to-shard-cluster/

  - include: prep-vars.yml

  - include: config-save.yml
    when: do_config|bool == true

  - include: replica-set-init.yml
    when: do_replica_set_init|bool == true

  - include: replica-set-shards.yml
    when: do_replica_set_shards|bool == true
