---

  - name: Stop services
    include: service-stop.yml

  - name: Upload replicaSetInit config file
    become: true
    template: src=../templates/mongod.conf.rsInit.j2 dest=/etc/mongod.conf owner=root group=root mode="u=rw,g=r,o=r"

  - name: Reset directories
    include: directories-init.yml
    no_log: true

  - name: Start the appropriate services
    include: service-start.yml

  - pause: seconds=5

  - name: Save the replicaSetInit template
    template: src=../templates/replicaSetInit.js.j2 dest=/tmp/replicaSetInit.js
    when: first_member == true

  - name: Run the replicaSetInit script
    shell: >
      mongo
      --port {{ rs_port }}
      < /tmp/replicaSetInit.js

    when: first_member == true
    register: res_rsi
    until: res_rsi.rc == 0
    retries: 5
    delay: 10

  - name: Kill the replicaSetInit script
    file: dest=/tmp/replicaSetInit.js
    when: first_member == true

  - name: Stop the daemon service
    become: true
    service: name=mongod state=stopped

  - name: Restore the mongodb configuration
    become: true
    template: src=../templates/mongod.conf.j2 dest=/etc/mongod.conf owner=root group=root mode="u=rw,g=r,o=r"

  - name: Restart the daemon service
    become: true
    service: name=mongod state=started
