---

  - name: Save the replica_set_shards script
    template: src=../templates/replica_set_shards.js.j2 dest=/tmp/replica_set_shards.js
    when: first_member == true

  - name: Run the replica_set_shards script
    shell: >
      mongo
      --host {{ server_fqdn }}
      --port {{ rs_port }}
      --ssl
      --sslPEMKeyFile {{ sc_chain_remote }}
      --sslCAFile {{ sc_interm_remote }}
      < /tmp/replica_set_shards.js

    when: first_member == true
    register: result
    until: result.rc == 0
    retries: 5
    delay: 3
