---

  - name: Start the daemon service, if needed
    become: true
    service: name=mongod state=started
    when: mongodb_type == "daemon"

  - name: Start the shard service, if needed
    become: true
    service: name=mongos state=started
    when: mongodb_type == "shard"
