---

  #
  # Disable any mongo services
  #
  - name: Stop the daemon service
    become: true
    service: name=mongod state=stopped

  - name: Stop the shard service, if applicable
    become: true
    service: name=mongos state=stopped
    when: mongodb_type == "shard"
