---

#  - stat: path=/srv/mongodb
#    register: stat_db

  - name: Kill logs
    become: true
    file: path={{ item }} state=absent  # state=empty
    with_items:
      - "{{ log_path_d }}"
      - "{{ log_path_s }}"

  - name: Status of data directory
    stat: path=/mnt/data
    register: stat_mnt

  - name: Delete srv directory
#    shell: rm -rf /srv/mongodb
    file: path=/srv/mongodb state=absent
    become: true

  - name: Delete mounted directory
#    shell: rm -rf /mnt/data/mongodb/
    file: path=/mnt/data/mongodb/ state=absent
    become: true
    when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir

  - name: Create db dir, basic
    file: path=/srv/mongodb state=directory mode=755 owner=mongodb group=mongodb
    when: stat_mnt.stat.isdir is not defined or stat_mnt.stat.isdir == false
    become: true

  - name: Create db dir, mounted
    file: path=/mnt/data/mongodb/ state=directory mode=755 owner=mongodb group=mongodb
    when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir == true
    become: true

  - name: Create link, if needed
    file: src=/mnt/data/mongodb dest=/srv/mongodb state=link mode=755 owner=mongodb group=mongodb
    when: stat_mnt.stat.isdir is defined and stat_mnt.stat.isdir|bool == true
    become: true
